#The weight you want the netherite horse armor to be in the loot table (bastion treasure). Requires /reload command to work if changed in game. Set to 0 to disable loot generation. (default: 8)
#Range: > 0
weight = 8
#The armor points you want for the netherite horse armor. (default: 13)
#Range: 1 ~ 30
protectionValue = 13

